// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	util "idev-cms-service/service/util"

	mock "github.com/stretchr/testify/mock"
)

// GenCode is an autogenerated mock type for the GenCode type
type GenCode struct {
	mock.Mock
}

// Generate provides a mock function with given fields: codeType, length
func (_m *GenCode) Generate(codeType util.GenCodeType, length int64) string {
	ret := _m.Called(codeType, length)

	var r0 string
	if rf, ok := ret.Get(0).(func(util.GenCodeType, int64) string); ok {
		r0 = rf(codeType, length)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GenerateWithPrefix provides a mock function with given fields: codeType, length, prefix
func (_m *GenCode) GenerateWithPrefix(codeType util.GenCodeType, length int64, prefix string) string {
	ret := _m.Called(codeType, length, prefix)

	var r0 string
	if rf, ok := ret.Get(0).(func(util.GenCodeType, int64, string) string); ok {
		r0 = rf(codeType, length, prefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
